### ISSUE TITLE
Not beeing able to set negative price and have negative quantity (products)

### ISSUE THREAD

**Issue by wiklundemil** [jacomoelLTU/Grupp9-D0018E#54]

**Comment by adalju-0** [comment]
Negative numbers on price and quantity as input are now disabled with html "min=0" tag. Remains to fix if quantity goes below zero when adding to caart

**Comment by adalju-0** [comment]
Quantity can no longer go below zero by a single user. I am not sure if it can go below if two different users have already added the product to their cart before it says soldout.

**Comment by adalju-0** [comment]
I have now tested and it can't go below zero but you can't add a product to your cart if someone else has the last item. 
I'll create a new issue for this

**Comment by adalju-0** [comment]
You can get negative quantity if one user adds to cart before another user completes purchase

**Comment by adalju-0** [comment]
Fixed.
